filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/tmp/*"

output.logstash:
  hosts: ["$HOST"]
  enabled: true
  # ssl.certificate_authorities: ["/cert/ca.crt"]
  # ssl.certificate: "/cert/filebeat.crt"
  # ssl.key: "/cert/filebeat.key"